"""add_audit_log_table

Revision ID: 90fadb6fef4f
Revises: 6e903e91a10e
Create Date: 2026-04-28 10:27:34.482754+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90fadb6fef4f'
down_revision: Union[str, Sequence[str], None] = '6e903e91a10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action', 't_audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_created_at', 't_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_t_audit_log_id'), 't_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_t_audit_log_user_id'), 't_audit_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_audit_log_user_id'), table_name='t_audit_log')
    op.drop_index(op.f('ix_t_audit_log_id'), table_name='t_audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='t_audit_log')
    op.drop_index('ix_audit_log_action', table_name='t_audit_log')
    op.drop_table('t_audit_log')
    # ### end Alembic commands ###