"""add rabc models

Revision ID: 6e903e91a10e
Revises:
Create Date: 2026-04-14 15:10:33.891167+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "6e903e91a10e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_class",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_t_class_id"), "t_class", ["id"], unique=False)
    op.create_table(
        "t_permission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("resource", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource", "action", name="uq_permission_resource_action"),
    )
    op.create_index(op.f("ix_t_permission_id"), "t_permission", ["id"], unique=False)
    op.create_table(
        "t_role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_t_role_id"), "t_role", ["id"], unique=False)
    op.create_table(
        "t_user",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_t_user_email"), "t_user", ["email"], unique=True)
    op.create_index(op.f("ix_t_user_id"), "t_user", ["id"], unique=False)
    op.create_table(
        "t_role_permission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["t_permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["t_role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_t_role_permission_id"), "t_role_permission", ["id"], unique=False)
    op.create_index(op.f("ix_t_role_permission_permission_id"), "t_role_permission", ["permission_id"], unique=False)
    op.create_index(op.f("ix_t_role_permission_role_id"), "t_role_permission", ["role_id"], unique=False)
    op.create_table(
        "t_user_role",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["t_class.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["t_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["t_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", "class_id", name="uq_user_role_class"),
    )
    op.create_index(op.f("ix_t_user_role_class_id"), "t_user_role", ["class_id"], unique=False)
    op.create_index(op.f("ix_t_user_role_id"), "t_user_role", ["id"], unique=False)
    op.create_index(op.f("ix_t_user_role_role_id"), "t_user_role", ["role_id"], unique=False)
    op.create_index(op.f("ix_t_user_role_user_id"), "t_user_role", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_t_user_role_user_id"), table_name="t_user_role")
    op.drop_index(op.f("ix_t_user_role_role_id"), table_name="t_user_role")
    op.drop_index(op.f("ix_t_user_role_id"), table_name="t_user_role")
    op.drop_index(op.f("ix_t_user_role_class_id"), table_name="t_user_role")
    op.drop_table("t_user_role")
    op.drop_index(op.f("ix_t_role_permission_role_id"), table_name="t_role_permission")
    op.drop_index(op.f("ix_t_role_permission_permission_id"), table_name="t_role_permission")
    op.drop_index(op.f("ix_t_role_permission_id"), table_name="t_role_permission")
    op.drop_table("t_role_permission")
    op.drop_index(op.f("ix_t_user_id"), table_name="t_user")
    op.drop_index(op.f("ix_t_user_email"), table_name="t_user")
    op.drop_table("t_user")
    op.drop_index(op.f("ix_t_role_id"), table_name="t_role")
    op.drop_table("t_role")
    op.drop_index(op.f("ix_t_permission_id"), table_name="t_permission")
    op.drop_table("t_permission")
    op.drop_index(op.f("ix_t_class_id"), table_name="t_class")
    op.drop_table("t_class")
    # ### end Alembic commands ###
