"""add system setting table

Revision ID: 9e422d11bdee
Revises: b7a4c9d2e1f3
Create Date: 2026-04-29 15:55:57.633962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e422d11bdee'
down_revision: Union[str, Sequence[str], None] = 'b7a4c9d2e1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_system_setting',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('system_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('copyright', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('page_title_template', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('logo_light_file_id', sa.Uuid(), nullable=True),
    sa.Column('logo_dark_file_id', sa.Uuid(), nullable=True),
    sa.Column('favicon_file_id', sa.Uuid(), nullable=True),
    sa.Column('login_background_file_id', sa.Uuid(), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('theme_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('layout_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('menu_collapsed_default', sa.Boolean(), nullable=False),
    sa.Column('fixed_header', sa.Boolean(), nullable=False),
    sa.Column('fixed_sidebar', sa.Boolean(), nullable=False),
    sa.Column('page_animation_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_home_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tab_view_enabled', sa.Boolean(), nullable=False),
    sa.Column('route_cache_enabled', sa.Boolean(), nullable=False),
    sa.Column('request_timeout_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favicon_file_id'], ['t_upload_file.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['login_background_file_id'], ['t_upload_file.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logo_dark_file_id'], ['t_upload_file.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logo_light_file_id'], ['t_upload_file.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_index(op.f('ix_t_system_setting_id'), 't_system_setting', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_system_setting_id'), table_name='t_system_setting')
    op.drop_table('t_system_setting')
    # ### end Alembic commands ###
