"""add upload_file table

Revision ID: ea0d5c6d048d
Revises: 90fadb6fef4f
Create Date: 2026-04-29 12:56:04.103824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ea0d5c6d048d'
down_revision: Union[str, Sequence[str], None] = '90fadb6fef4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_upload_file',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('stored_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('storage_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('public_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_upload_file_id'), 't_upload_file', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_upload_file_id'), table_name='t_upload_file')
    op.drop_table('t_upload_file')
    # ### end Alembic commands ###
